### ISSUE TITLE
Python3 Specific Code

### ISSUE THREAD

**Issue by nishithbsk** [Jabberwockyll/deep_rl_ale#2]
Hi,

Thanks for a great library!

Could you explain what line 39 of `experiments.py` should be doing?
`agent.test_state = list(next(zip(*reset)))`
If I am not mistaken, reset is a list of states where each state is (s, action, reward, terminal) and line 39 is helping the while loop iterate over this list of lists.

Thanks!

**Comment by jonathonbyrd** [comment]
Hi nishithbsk,

I think you got it.  reset is a list of transitions (frame-action-reward-terminal).  I just want the frames/observations to give the agent as the initial state after resetting the game.  Zipping the unpacked list returns an iterator of tuples (frames, actions, rewards, terminals), and I just want the first tuple (the observations), which next() returns.  Then list() turns it into a list.

This line of code isn't particularly reader-friendly, and I plan on refactoring a lot of deep_rl_ale next week.
